
FROM php:7.4-apache

# Update system core
#RUN apt update -y && apt install nano net-tools telnet -y && apt upgrade -y
#RUN docker-php-ext-install pdo pdo_mysql bcmath && docker-php-ext-enable pdo pdo_mysql bcmath 
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN a2enmod authz_groupfile rewrite

CMD chmod -R 777 /var/www/html/ && \
    chown www-data:www-data /var/www/html/ -R && \
    /etc/init.d/apache2 restart && \
    tail -F /var/log/apache2/access.log 



