version: "3.1"

services:
  
  #db mysite
  mysitedb:
    image: mysitedb:1.0
    container_name: mysite
    ports:
      - "3307:3306"
    restart: always
    environment:
      MARIADB_USER: finsoft
      MARIADB_PASSWORD: finsoft
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: finsoft
    networks:
      - mysitedocker
    volumes:
      - /home/finsoft/finsoft-repo/cv_docker:/opt:rw
  #mysite
  mysitedocker:

    container_name: mysitedocker-micro
    image: mysite:1.1
    ports:
      - "8080:80"
    networks:
      - mysitedocker
    depends_on:
      - mysitedb
    volumes:
      - /home/finsoft/finsoft-repo/cv_docker:/var/www/html:rw

networks:
      mysitedocker:
